name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 触发自动构建的分支，可根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 登录到 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        cd docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/zasper:latest .

    # 推送 Docker 镜像到 Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/zasper:latest
